modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "pumpkinclient"
version = "${version}"
displayName = "PumpkinClient"
authors = "Missng_Love"
description = '''

'''
#logoFile = ""

[[dependencies.pumpkinclient]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pumpkinclient]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pumpkinclient]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pumpkinclient]]
modId = "cloth_config"
type = "required"
versionRange = "[15,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "pumpkinclient.mixins.json"
